"""simulation phase 2

Revision ID: d4346b29632c
Revises: 0002_vin_index
Create Date: 2026-09-22 18:36:26.471350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4346b29632c'
down_revision: Union[str, Sequence[str], None] = '0002_vin_index'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('hw_b_failure_probability', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_campaign_id'), 'simulation_runs', ['campaign_id'], unique=False)
    op.create_table('ota_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('ecu_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('installation_step', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=False),
    sa.Column('hardware_revision', sa.String(length=100), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('network_quality', sa.Integer(), nullable=False),
    sa.Column('free_storage_mb', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('simulation_id', 'vehicle_id', 'sequence', name='uq_event_sequence')
    )
    op.create_index(op.f('ix_ota_events_simulation_id'), 'ota_events', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_ota_events_vehicle_id'), 'ota_events', ['vehicle_id'], unique=False)
    op.create_table('simulation_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('rollback_count', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('evaluation_note', sa.String(length=1000), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'stage_number', name='uq_simulation_stage')
    )
    op.create_index(op.f('ix_simulation_stages_simulation_id'), 'simulation_stages', ['simulation_id'], unique=False)
    op.create_table('simulation_vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('ecu_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_index', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'vehicle_id', name='uq_simulation_vehicle_id'),
    sa.UniqueConstraint('simulation_id', 'vehicle_index', name='uq_simulation_vehicle_index')
    )
    op.create_index(op.f('ix_simulation_vehicles_simulation_id'), 'simulation_vehicles', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_vehicles_simulation_id'), table_name='simulation_vehicles')
    op.drop_table('simulation_vehicles')
    op.drop_index(op.f('ix_simulation_stages_simulation_id'), table_name='simulation_stages')
    op.drop_table('simulation_stages')
    op.drop_index(op.f('ix_ota_events_vehicle_id'), table_name='ota_events')
    op.drop_index(op.f('ix_ota_events_simulation_id'), table_name='ota_events')
    op.drop_table('ota_events')
    op.drop_index(op.f('ix_simulation_runs_campaign_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
