"""stage evaluator

Revision ID: fe222d629404
Revises: d4346b29632c
Create Date: 2026-09-22 18:45:56.786863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe222d629404'
down_revision: Union[str, Sequence[str], None] = 'd4346b29632c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_stages', sa.Column('evaluated_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_stages', 'evaluated_by')
    # ### end Alembic commands ###
