import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ThemeProvider } from '@mui/material'
import { App } from './App'
import { theme } from './theme'
import { OperationalSessionProvider } from './SessionContext'

const simulationId='dd788fea-465f-4ce5-82f7-5dc1ed3cab87'
const campaignId='b7ffd55f-6fa9-437b-b5a4-04466492d874'
const incidentId='2eda53a0-2aab-49aa-8843-c76a7179bbe3'
const workflowId='f39476d2-3f59-49d0-bb3b-19278b874e99'
const context={context_id:simulationId,source:'LIVE_SIMULATION',environment:'SIMULATED',session_id:'39062b0e-dc01-4a16-9fd3-5a03d6dd4bd7',campaign_id:campaignId,campaign_name:'BatteryManager Controlled Run',campaign_status:'draft',simulation_id:simulationId,simulation_status:'WAITING_FOR_HUMAN_APPROVAL',incident_id:incidentId,workflow_id:workflowId,workflow_status:'WAITING_FOR_HUMAN_APPROVAL',approval_status:'PENDING',software_name:'BatteryManager',software_version:'2.4.0',stage_number:1,vehicle_count:30,progress_count:30,success_count:24,failure_count:6,rollback_count:3,failure_rate:.2,evidence_count:253,global_confidence:.620644,actions_executed:0,created_by:'ota-operator',created_at:'2026-09-23T19:24:21Z',updated_at:'2026-09-23T19:24:24Z'}
const dashboard={scope:'active',active_context:context,campaign_count:1,tracked_vehicle_count:30,simulation_participant_count:30,progress_count:30,success_count:24,failure_count:6,rollback_count:3,success_rate:.8,failure_rate:.2,open_incident_count:1,waiting_workflow_count:1,services:{api:'opérationnel',postgresql:'opérationnel',redis:'opérationnel',celery_worker:'opérationnel'}}
const campaign={id:campaignId,name:context.campaign_name,status:'draft',canary_percentage:100,created_at:context.created_at,source:'LIVE_SIMULATION',session_id:context.session_id,software_package:{id:'package',name:'BatteryManager',version:'2.4.0',target_hardware:'SIMULATED_MULTI_HW'},simulation:{id:simulationId,status:'COMPLETED',current_stage:1,failure_threshold:.2,stages:[{id:'stage',stage_number:1,vehicle_count:30,status:'COMPLETED',success_count:24,failure_count:6,rollback_count:3,approved:null,evaluated_by:null,evaluated_at:null}]}}
const incident={id:incidentId,campaign_id:campaignId,simulation_id:simulationId,stage_number:1,status:'open',severity:'high',title:'Failure threshold reached',failure_rate:.2,threshold:.2,anomaly_score:null,created_at:context.created_at,vehicle_count:30,success_count:24,failure_count:6,rollback_count:3,linked_event_count:253,failure_event_count:6,normalized_errors:[{error_code:'MEMORY_LAYOUT_MISMATCH',installation_step:'MEMORY_VALIDATION',count:3}],hardware_distribution:[{hardware_revision:'HW_REV_A',total:27,success:24,failure:3},{hardware_revision:'HW_REV_B',total:3,success:0,failure:3}]}
const evidence=Array.from({length:3},(_,index)=>({evidence_id:`evidence-${index}`,evidence_type:'FAILED_VEHICLE_TIMELINE',event_id:`event-${index}`,vehicle_id:`vehicle-${index}`,sequence:index+1,timestamp:context.updated_at,installation_step:'MEMORY_VALIDATION',error_code:'MEMORY_LAYOUT_MISMATCH',hardware_revision:'HW_REV_B',software_version:'2.4.0',battery_level:82,network_quality:88,free_storage_mb:4096}))
const actions=['PAUSE_CAMPAIGN','EXCLUDE_INCOMPATIBLE_VEHICLES','ASSIGN_CORRECTIVE_PACKAGE','REQUEST_ADDITIONAL_INVESTIGATION'].map(action=>({action,status:'PROPOSED',requires_human_approval:true,reason:'Validation humaine requise.',executed:false,evidence_ids:['evidence-0']}))
const workflow={workflow_id:workflowId,incident_id:incidentId,campaign_id:campaignId,canary_stage_id:'stage',current_agent:null,workflow_status:'WAITING_FOR_HUMAN_APPROVAL',failed_vehicle_ids:Array(6).fill('failed'),successful_vehicle_ids:Array(24).fill('success'),normalized_errors:[{error_code:'MEMORY_LAYOUT_MISMATCH',count:3}],timeline:Array(30).fill({}),correlations:[{factor:'hardware_revision',level:'HW_REV_B',risk_ratio:7}],hypotheses:[{hypothesis_id:'hypothesis',factor:'hardware_revision',level:'HW_REV_B',statement:'Association probable.',confidence:.620644,rank:1,evidence_ids:['evidence-0'],score_components:{association_strength:.7}}],evidence_ids:Array.from({length:253},(_,i)=>`evidence-${i}`),confidence_components:{association_strength:.701839},global_confidence:.620644,recommended_actions:actions,approval_status:'PENDING',retry_count:0,last_error:null,created_at:context.created_at,updated_at:context.updated_at}
const history=['MONITORING','LOG_ANALYSIS','CORRELATION','RCA','DECISION'].map((agent,index)=>({id:`history-${index}`,sequence:index+1,agent,event_type:'AGENT_COMPLETED',input_summary:{evidence_count:index?253:0},output_summary:{evidence_count:253,result:'completed'},duration_ms:[742,131,94,40,91][index],error_type:null,error_message:null,created_at:context.updated_at}))
const executions=history.map((row,index)=>({id:`execution-${index}`,agent_type:row.agent,objective:`Objectif ${row.agent}`,status:'COMPLETED',current_state:'STOP',observation:{},plan:{operational_summary:`Plan ${row.agent}`},selected_tool:`tool-${index}`,tool_call_ids:[],validation_result:{valid:true},runtime_retry_count:0,stop_reason:null,tools_allowed:[`tool-${index}`],tools_used:[`tool-${index}`],input_payload:row.input_summary,output_payload:row.output_summary,evidence_ids:['evidence-0'],validations:['MESSAGE_CONTRACT'],attempt:1,duration_ms:row.duration_ms,proposed_next_state:history[index+1]?.agent??'WAITING_FOR_HUMAN_APPROVAL',output_source:'DETERMINISTIC_FALLBACK',error_code:null,created_at:row.created_at,completed_at:row.created_at}))
const messages=history.map((row,index)=>({id:`message-${index}`,sender_agent:row.agent,receiver_agent:history[index+1]?.agent??'HUMAN',message_type:['INCIDENT_DETECTED','NORMALIZED_FAILURES_READY','CORRELATIONS_READY','ROOT_CAUSES_READY','HUMAN_APPROVAL_REQUIRED'][index],summary:`${row.agent} message`,payload:row.output_summary,evidence_ids:['evidence-0'],tool_call_ids:[],correlation_id:workflowId,sequence_number:index+1,validation_status:'VALIDATED',created_at:row.created_at,consumed_at:index<4?row.created_at:null}))
const tools=executions.map((execution,index)=>({id:`tool-execution-${index}`,agent_execution_id:execution.id,agent_type:execution.agent_type,tool_name:`tool-${index}`,mode:'READ_ONLY',input_payload:execution.input_payload,output_payload:execution.output_payload,status:'COMPLETED',duration_ms:execution.duration_ms,sequence_number:1,created_at:execution.created_at}))
const llmStatus={provider:'nvidia',model:'z-ai/glm-5.3',hostname:'integrate.api.nvidia.com',configured:true,reachable:false,authorized:false,latency_ms:null,structured_output_supported:false,error_code:null}
const maturity={scale:[['M0','Non défini'],['M1','Prototype local'],['M2','Intégration initiale'],['M3','Workflow supervisé'],['M4','Fonctionnement validé en environnement simulé'],['M5','Production automobile validée']].map(([level,label])=>({level,label})),agents:history.map(row=>({agent:row.agent,name:row.agent,role:'Rôle déterministe',current_level:'M4',execution_status:'COMPLETED',criteria:{M4:{satisfied:true,label:'Workflow complet'}},technical_evidence:['evidence_count=253'],associated_tests:['test_agentic_workflow.py'],last_execution:row.created_at,duration_ms:row.duration_ms,input_summary:row.input_summary,output_summary:row.output_summary,recent_errors:[],limitations:['Environnement simulé'],next_level:'M5',next_level_conditions:['Validation sur véhicule réel']})),certification_notice:'Échelle interne non certifiante.',m5_available:false}
const audit={context,entries:[{id:'audit-1',timestamp:context.created_at,category:'SIMULATION',actor:'ota-operator',action:'LIVE_SESSION_CREATED',status:'CREATED',summary:'Session créée',details:{}},...history.map(row=>({id:row.id,timestamp:row.created_at,category:'AGENT',actor:row.agent,action:row.event_type,status:'COMPLETED',summary:'Résultat persistant',details:{duration_ms:row.duration_ms}}))]}
const reports=[{report_id:'report-id',incident_id:incidentId,workflow_id:workflowId,explanation_id:'explanation',version:1,template_version:'incident-report-v1.1',pdf_sha256:'f6e456ecf62319265679280f82b9516fcb9c59222c711d9e39c595d7194589cc',generated_at:context.updated_at,download_url:'/reports/report-id/pdf',source:'DETERMINISTIC_FALLBACK'}]
const capabilities={operation_mode:'live_simulation',can_create_simulation:true,can_launch_simulation:true,can_start_investigation:true,can_review_recommendations:true,can_execute_real_ota:false}

let calls:Array<{url:string;method:string}>=[]
function responseFor(url:string){const path=url.replace(/^\/_backend/,'');if(path==='/api/v1/ui/contexts?scope=all')return[context];if(path.startsWith('/api/v1/ui/dashboard?'))return dashboard;if(path==='/api/v1/ui/campaigns?scope=all')return[campaign];if(path===`/api/v1/ui/campaigns/${campaignId}`)return campaign;if(path.includes('/api/v1/ui/vehicles?'))return{total:0,items:[]};if(path===`/api/v1/ui/incidents/${incidentId}`)return incident;if(path===`/incidents/${incidentId}/evidence`)return evidence;if(path===`/workflows/${workflowId}`)return workflow;if(path===`/workflows/${workflowId}/history`)return history;if(path===`/workflows/${workflowId}/executions`)return executions;if(path===`/workflows/${workflowId}/messages`)return messages;if(path===`/workflows/${workflowId}/tools`)return tools;if(path==='/api/v1/llm/status'||path==='/api/v1/llm/test')return llmStatus;if(path==='/agent-maturity')return maturity;if(path===`/api/v1/ui/incidents/${incidentId}/reports`)return reports;if(path===`/api/v1/ui/audit?simulation_id=${simulationId}`)return audit;if(path==='/frontend/capabilities')return capabilities;return undefined}
function mockApi(fail=false){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);calls.push({url,method:init?.method??'GET'});if(fail)return new Response(JSON.stringify({detail:'Service indisponible'}),{status:503,headers:{'Content-Type':'application/json'}});const payload=responseFor(url);return payload===undefined?new Response('{}',{status:404}):new Response(JSON.stringify(payload),{status:200,headers:{'Content-Type':'application/json'}})}))}
function renderAt(path:string){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<ThemeProvider theme={theme}><QueryClientProvider client={client}><OperationalSessionProvider><MemoryRouter initialEntries={[path]}><App/></MemoryRouter></OperationalSessionProvider></QueryClientProvider></ThemeProvider>)}

beforeEach(()=>{calls=[];localStorage.clear();Object.assign(llmStatus,{configured:true,reachable:false,authorized:false,structured_output_supported:false,error_code:null});mockApi()})
afterEach(()=>vi.unstubAllGlobals())

describe('Interface opérationnelle AIGATOS',()=>{
  it('affiche uniquement les huit fonctions opérationnelles',async()=>{renderAt('/');await screen.findByRole('heading',{name:'Tableau de bord'});for(const label of ['Tableau de bord','Campagnes','Véhicules','Simulation','Incidents','Analyse agentique','Rapports','Audit'])expect(screen.getAllByText(label).length).toBeGreaterThan(0);expect(document.body).not.toHaveTextContent(/Jury|Hackathon|Mode démonstration|Read Only Demo/i)})
  it('restitue les métriques cohérentes de la session active',async()=>{renderAt('/');expect(await screen.findByText('24')).toBeInTheDocument();expect(screen.getByText('6')).toBeInTheDocument();expect(screen.getByText('3')).toBeInTheDocument();expect(screen.getAllByText(/20\s*%/).length).toBeGreaterThan(0);expect(screen.getAllByText(context.campaign_name).length).toBeGreaterThan(0)})
  it('conserve la sélection de contexte pendant la navigation',async()=>{renderAt('/campaigns');await screen.findByText(context.campaign_name);expect(localStorage.getItem('aigatos.activeSimulationId')).toBe(simulationId);expect(calls.some(call=>call.url.includes('/contexts?scope=all'))).toBe(true)})
  it('charge une configuration de simulation sans lancer automatiquement',async()=>{renderAt('/simulation');await screen.findByRole('heading',{name:'Nouvelle simulation OTA'});fireEvent.click(screen.getByRole('button',{name:'Charger une configuration de référence'}));expect(screen.getByLabelText('Nom de campagne')).toHaveValue('BatteryManager Controlled Run');expect(calls.every(call=>call.method==='GET'||(call.method==='POST'&&call.url.includes('/api/v1/llm/test')))).toBe(true)})
  it('n’affiche l’assistant qu’après un probe structuré réussi et conserve le formulaire manuel',async()=>{Object.assign(llmStatus,{reachable:true,authorized:true,structured_output_supported:true,error_code:null});renderAt('/simulation');await screen.findByRole('heading',{name:'Nouvelle simulation OTA'});expect(await screen.findByText(/Assistant disponible/)).toBeInTheDocument();const promptField=screen.getByLabelText('Description en langage naturel');expect(promptField).toBeInTheDocument();fireEvent.change(promptField,{target:{value:'Créer un brouillon pour une flotte de test.'}});expect(screen.getByRole('button',{name:'Générer le brouillon'})).toBeEnabled();expect(calls.some(call=>call.url.includes('/api/v1/llm/test')&&call.method==='POST')).toBe(true);expect(screen.getByLabelText('Nom de campagne')).toBeInTheDocument()})
  it('masque entièrement l’assistant après un échec provider et laisse la configuration manuelle utilisable',async()=>{Object.assign(llmStatus,{reachable:false,authorized:false,structured_output_supported:false,error_code:'LLM_CONNECTION_FAILED'});renderAt('/simulation');await screen.findByRole('heading',{name:'Nouvelle simulation OTA'});expect(await screen.findByRole('status')).toHaveTextContent(/Assistant IA indisponible/);expect(screen.queryByLabelText('Description en langage naturel')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Générer le brouillon'})).not.toBeInTheDocument();expect(screen.getByLabelText('Nom de campagne')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Charger une configuration de référence'})).toBeEnabled()})
  it('affiche l’incident depuis le contexte sans valeur locale de substitution',async()=>{renderAt('/incidents');expect(await screen.findByText('253')).toBeInTheDocument();expect(screen.getAllByText('MEMORY_LAYOUT_MISMATCH').length).toBeGreaterThan(0);expect(screen.getAllByText(/20\s*%/).length).toBeGreaterThan(0)})
  it('fusionne workflow, transmissions et maturité sans contrôle de replay',async()=>{renderAt('/analysis');expect(await screen.findByRole('heading',{name:'Analyse agentique'})).toBeInTheDocument();expect(await screen.findByText('Transmissions entre agents')).toBeInTheDocument();expect(screen.getAllByText(/M4 · environnement simulé/)).toHaveLength(5);expect(screen.getByText(/M5 — Non atteint/)).toBeInTheDocument();for(const label of ['Replay','Pause','Recommencer','Étape suivante','Étape précédente'])expect(screen.queryByRole('button',{name:label})).not.toBeInTheDocument();expect(document.body).not.toHaveTextContent(/progression vers M5|80 %|90 %/i)})
  it('affiche les rapports de l’incident actif',async()=>{renderAt('/reports');await screen.findByText(reports[0].pdf_sha256,{}, {timeout:5_000});const link=screen.getByRole('link',{name:'Télécharger le PDF'});expect(link).toHaveAttribute('href','/_backend/reports/report-id/pdf')})
  it('affiche l’historique d’audit du contexte actif',async()=>{renderAt('/audit');expect(await screen.findByText('LIVE SESSION CREATED')).toBeInTheDocument();expect(screen.getByText('MONITORING')).toBeInTheDocument()})
  it('gère une API indisponible avec un état explicite',async()=>{mockApi(true);renderAt('/');expect(await screen.findByText(/API indisponible/)).toBeInTheDocument()})
  it('n’expose aucun secret et ne déclenche aucune mutation',async()=>{renderAt('/analysis');await screen.findByRole('heading',{name:'Analyse agentique'});expect(document.body.textContent).not.toMatch(/API[_ -]?KEY|Authorization|Bearer\s/i);expect(calls.every(call=>call.method==='GET')).toBe(true);expect(workflow.recommended_actions.every(item=>item.executed===false)).toBe(true)})
  it('redirige les anciennes vues de workflow vers l’analyse consolidée',async()=>{renderAt(`/workflows/${workflowId}/interaction`);expect(await screen.findByRole('heading',{name:'Analyse agentique'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Replay'})).not.toBeInTheDocument()})
  it('isole la liste des véhicules sur la simulation active',async()=>{renderAt('/vehicles');await screen.findByRole('heading',{name:'Véhicules'});await waitFor(()=>expect(calls.some(call=>call.url.includes(`/api/v1/ui/vehicles?simulation_id=${simulationId}`))).toBe(true));expect(calls.some(call=>call.url.includes('scope=all'))).toBe(true)})
  it('utilise les mêmes identifiants et valeurs API entre les pages',async()=>{const first=renderAt('/');await screen.findByText('24');first.unmount();const second=renderAt('/incidents');await screen.findByText('253');second.unmount();renderAt('/analysis');await screen.findByRole('heading',{name:'Analyse agentique'});expect(workflow.incident_id).toBe(context.incident_id);expect(workflow.workflow_id).toBe(context.workflow_id);expect(workflow.approval_status).toBe(context.approval_status);expect(workflow.evidence_ids).toHaveLength(context.evidence_count);expect(workflow.recommended_actions.filter(item=>item.executed)).toHaveLength(context.actions_executed)})
})
