import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ThemeProvider } from '@mui/material'
import { App } from './App'
import { theme } from './theme'
import { INCIDENT_ID, REPORT_ID, SCORE, WORKFLOW_ID } from './constants'

const dashboard={campaign_count:2,tracked_vehicle_count:200,simulation_participant_count:40,success_count:34,failure_count:6,success_rate:.85,failure_rate:.15,open_incident_count:1,waiting_workflow_count:1,services:{api:'opérationnel',postgresql:'opérationnel',redis:'opérationnel',celery_worker:'indisponible'}}
const campaign={id:'campaign',name:'BatteryManager demo',status:'draft',canary_percentage:5,created_at:'2026-09-23T10:00:00Z',software_package:{id:'package',name:'BatteryManager',version:'2.4.0',target_hardware:'HW_REV_A'},simulation:{id:'simulation',status:'awaiting_evaluation',current_stage:2,failure_threshold:.2,stages:[{id:'stage1',stage_number:1,vehicle_count:10,status:'approved',success_count:9,failure_count:1,rollback_count:1,approved:true,evaluated_by:'reviewer',evaluated_at:'2026-09-23T09:00:00Z'},{id:'stage2',stage_number:2,vehicle_count:30,status:'awaiting_evaluation',success_count:24,failure_count:6,rollback_count:3,approved:null,evaluated_by:null,evaluated_at:null},{id:'stage3',stage_number:3,vehicle_count:60,status:'pending',success_count:0,failure_count:0,rollback_count:0,approved:null,evaluated_by:null,evaluated_at:null}]}}
const vehicle={id:'vehicle',vin:'AIGATOS0000000001',model:'AIGATOS EV',region:null,hardware_revision:'HW_REV_B',ecu:{id:'ecu',name:'BatteryManager'},current_version:'2.3.0',target_version:'2.4.0',ota_status:'FAILURE',rolled_back:true,simulation_id:'simulation',campaign_id:'campaign',timeline:[{event_id:'event',timestamp:'2026-09-23T10:00:00Z',event_type:'FAILURE',installation_step:'MEMORY_VALIDATION',error_code:'MEMORY_LAYOUT_MISMATCH',battery_level:82,network_quality:88,free_storage_mb:4096}]}
const incident={id:INCIDENT_ID,campaign_id:'campaign',simulation_id:'simulation',stage_number:2,status:'open',severity:'high',title:'Threshold reached',failure_rate:.2,threshold:.2,anomaly_score:null,created_at:'2026-09-23T10:00:00Z',vehicle_count:30,success_count:24,failure_count:6,rollback_count:3,linked_event_count:259,failure_event_count:6,normalized_errors:[{error_code:'MEMORY_LAYOUT_MISMATCH',installation_step:'MEMORY_VALIDATION',count:3}],hardware_distribution:[{hardware_revision:'HW_REV_A',total:27,success:24,failure:3},{hardware_revision:'HW_REV_B',total:3,success:0,failure:3}]}
const primaryEvidence=['779e64ea-e83b-4c92-b313-fbab5fdbdcba','8fca5c3a-c6fb-4bfe-a226-79ed37df2277','e16c42b8-dea1-439f-a100-8ada1b0f65a7']
const evidence=primaryEvidence.map((evidence_id,index)=>({evidence_id,evidence_type:'FAILED_VEHICLE_TIMELINE',event_id:`event-${index}`,vehicle_id:`vehicle-${index}`,sequence:index+1,timestamp:'2026-09-23T10:00:00Z',installation_step:'MEMORY_VALIDATION',error_code:'MEMORY_LAYOUT_MISMATCH',hardware_revision:'HW_REV_B',software_version:'2.4.0',battery_level:82,network_quality:88,free_storage_mb:4096}))
const recommendations=['PAUSE_CAMPAIGN','EXCLUDE_INCOMPATIBLE_VEHICLES','ASSIGN_CORRECTIVE_PACKAGE','REQUEST_ADDITIONAL_INVESTIGATION'].map(action=>({action,status:'PROPOSED',requires_human_approval:true,reason:'Advisory only',executed:false,evidence_ids:[evidence[0].evidence_id]}))
const workflow={workflow_id:WORKFLOW_ID,incident_id:INCIDENT_ID,campaign_id:'campaign',canary_stage_id:'stage2',current_agent:null,workflow_status:'WAITING_FOR_HUMAN_APPROVAL',failed_vehicle_ids:Array.from({length:6},(_,i)=>`f${i}`),successful_vehicle_ids:Array.from({length:24},(_,i)=>`s${i}`),normalized_errors:Array.from({length:4},(_,i)=>({error_code:`ERROR_${i}`})),timeline:Array.from({length:30},(_,i)=>({vehicle_id:`v${i}`})),correlations:[{factor:'hardware_revision',level:'HW_REV_A',exposed_count:27,failures:3,risk_ratio:.142857,confidence_interval_95:[.05,.407]},{factor:'hardware_revision',level:'HW_REV_B',exposed_count:3,failures:3,risk_ratio:7,confidence_interval_95:[2.4552929468790605,19.956885414542583]}],hypotheses:Array.from({length:4},(_,i)=>({hypothesis_id:`h${i}`,factor:i?'telemetry':'hardware_revision',level:i?'LOW':'HW_REV_B',statement:'Association probable, non causale.',confidence:i?.31117:SCORE,rank:i+1,evidence_ids:primaryEvidence,score_components:{association_strength:.7}})),evidence_ids:primaryEvidence,confidence_components:{association_strength:.701839,failure_support:.5,error_consistency:.5,step_consistency:.5,evidence_coverage:1},global_confidence:SCORE,recommended_actions:recommendations,approval_status:'PENDING',retry_count:0,last_error:null,created_at:'2026-09-23T10:00:00Z',updated_at:'2026-09-23T10:01:00Z'}
const history=['MONITORING','LOG_ANALYSIS','CORRELATION','RCA','DECISION'].map((agent,i)=>({id:`history-${i}`,sequence:i+1,agent,event_type:'COMPLETED',input_summary:{workflow_status:'QUEUED',evidence_count:i?259:0},output_summary:{evidence_count:259,stage:i+1},duration_ms:[103,67,126,53,34][i],error_type:null,error_message:null,created_at:'2026-09-23T10:00:00Z'}))
const reports=[{report_id:REPORT_ID,incident_id:INCIDENT_ID,workflow_id:WORKFLOW_ID,explanation_id:'abe00f91-84db-4e05-a865-d79876c1b38a',version:2,template_version:'incident-report-v1.1',pdf_sha256:'f6e456ecf62319265679280f82b9516fcb9c59222c711d9e39c595d7194589cc',generated_at:'2026-09-23T13:31:41Z',download_url:`/reports/${REPORT_ID}/pdf`,source:'DETERMINISTIC_FALLBACK'}]
const explanation={id:'abe00f91-84db-4e05-a865-d79876c1b38a',workflow_id:WORKFLOW_ID,incident_id:INCIDENT_ID,provider:'nvidia',model_name:'z-ai/glm-5.3',prompt_version:'phase4a-v1',source:'DETERMINISTIC_FALLBACK',status:'FALLBACK_TIMEOUT',duration_ms:1000,created_at:'2026-09-23T11:34:44Z',output:{incident_summary:'6 failed',probable_root_cause:'Cause probable : incompatibilité associée à HW_REV_B.',confidence_interpretation:`Score ${SCORE}`,evidence_citations:[{evidence_id:evidence[0].evidence_id,statement:'Preuve PostgreSQL validée.'}],alternative_hypotheses:[],recommended_next_steps:recommendations.map(x=>x.action),limitations:['Corrélation ne signifie pas causalité.'],generated_at:'2026-09-23T11:34:44Z',model_name:'z-ai/glm-5.3',prompt_version:'phase4a-v1'}}
const capabilities={operation_mode:'live_simulation',can_create_simulation:true,can_launch_simulation:true,can_start_investigation:true,can_review_recommendations:true,can_execute_real_ota:false}
const maturity={scale:['M0','M1','M2','M3','M4','M5'].map((level,index)=>({level,label:['Concept','Implémenté','Testé unitairement','Intégré et persistant','Démontré de bout en bout','Validé en production automobile'][index]})),agents:['MONITORING','LOG_ANALYSIS','CORRELATION','RCA','DECISION'].map(agent=>({agent,name:`${agent} Agent`,current_level:'M4',execution_status:'COMPLETED',criteria:{M1:{satisfied:true,label:'Implémentation présente'},M2:{satisfied:true,label:'Tests unitaires associés'},M3:{satisfied:true,label:'Intégration persistante'},M4:{satisfied:true,label:'Workflow complet'},M5:{satisfied:false,label:'Validation automobile'}},technical_evidence:['ota_actions_executed=0'],associated_tests:['test_agentic_workflow.py'],last_execution:'2026-09-23T10:00:00Z',execution_success_rate:1,recent_errors:[],limitations:['Simulé'],next_level:'M5',progress_to_next_level:0,next_level_conditions:['Validation sur véhicule réel']})),certification_notice:'Échelle interne non certifiante.',m5_available:false}

const routes:Record<string,unknown>={
  '/frontend/capabilities':capabilities,
  '/agent-maturity':maturity,
  '/api/v1/ui/dashboard':dashboard,
  '/api/v1/ui/campaigns':[campaign],
  '/api/v1/ui/campaigns?scope=all':[campaign],
  '/api/v1/ui/campaigns/campaign':campaign,
  '/api/v1/ui/vehicles?limit=250':{total:1,items:[vehicle]},
  '/api/v1/ui/vehicles?scope=all&limit=250':{total:1,items:[vehicle]},
  '/api/v1/ui/vehicles/vehicle':vehicle,
  [`/api/v1/ui/incidents/${INCIDENT_ID}`]:incident,
  [`/incidents/${INCIDENT_ID}/evidence`]:evidence,
  [`/workflows/${WORKFLOW_ID}`]:workflow,
  [`/workflows/${WORKFLOW_ID}/history`]:history,
  [`/api/v1/ui/incidents/${INCIDENT_ID}/reports`]:reports,
  [`/api/v1/ui/incidents/${INCIDENT_ID}/explanation`]:explanation,
}
let calls:Array<{url:string;method:string}>=[]
function mockApi(fail=false){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);calls.push({url,method:init?.method??'GET'});if(fail)return new Response(JSON.stringify({detail:'Service indisponible'}),{status:503,headers:{'Content-Type':'application/json'}});const payload=routes[url.replace(/^\/_backend/,'')];return payload===undefined?new Response('{}',{status:404}):new Response(JSON.stringify(payload),{status:200,headers:{'Content-Type':'application/json'}})}))}
function renderAt(path:string){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<ThemeProvider theme={theme}><QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><App/></MemoryRouter></QueryClientProvider></ThemeProvider>)}

beforeEach(()=>{calls=[];mockApi()})
afterEach(()=>vi.unstubAllGlobals())

describe('Interface AIGATOS Phase 5',()=>{
  it('dérive le mode Simulation Live des capabilities',async()=>{renderAt('/');expect((await screen.findAllByText('SIMULATION LIVE')).length).toBeGreaterThan(0);expect(screen.getByText('LAB LIVE')).toBeInTheDocument();expect(screen.getByText(/Aucune action OTA réelle/)).toBeInTheDocument()})
  it('charge le scénario Jury sans créer ni lancer automatiquement',async()=>{renderAt('/live-simulation');await screen.findByRole('heading',{name:'Nouvelle simulation OTA'});fireEvent.click(screen.getByRole('button',{name:'Charger le scénario Jury'}));expect(screen.getByLabelText('Nom de campagne')).toHaveValue('BatteryManager Live Jury');expect(screen.getByLabelText('Version cible')).toHaveValue('2.4.0');expect(calls.every(call=>call.method==='GET')).toBe(true)})
  it('affiche M4 séparément du statut et interdit M5',async()=>{renderAt('/agent-maturity');expect(await screen.findByRole('heading',{name:'Maturité des agents'})).toBeInTheDocument();expect(await screen.findAllByText('M4 simulé')).toHaveLength(5);expect(screen.getByText('M5')).toBeInTheDocument();expect(screen.getAllByText('Non').length).toBeGreaterThanOrEqual(5)})
  it('affiche le dashboard et les états de service',async()=>{renderAt('/');expect(await screen.findByText('200')).toBeInTheDocument();expect(screen.getAllByText(/Postgresql/i).length).toBeGreaterThan(0);expect(screen.getAllByText('opérationnel').length).toBeGreaterThan(0)})
  it('rend les listes et détails campagne et véhicule sans données inventées',async()=>{const first=renderAt('/campaigns');expect(await screen.findByText('BatteryManager demo')).toBeInTheDocument();first.unmount();const second=renderAt('/campaigns/campaign');expect(await screen.findByText('Canary 3')).toBeInTheDocument();second.unmount();const third=renderAt('/vehicles');expect(await screen.findByText('Non renseignée')).toBeInTheDocument();third.unmount();renderAt('/vehicles/vehicle');expect(await screen.findByText('MEMORY_LAYOUT_MISMATCH')).toBeInTheDocument()})
  it('rend l’incident avec les valeurs PostgreSQL attendues',async()=>{renderAt(`/incidents/${INCIDENT_ID}`);expect(await screen.findByText('259')).toBeInTheDocument();expect(screen.getAllByText('MEMORY_LAYOUT_MISMATCH').length).toBeGreaterThan(0);expect(screen.getByText('Indisponible')).toBeInTheDocument()})
  it('rend les cinq agents et le statut final du workflow',async()=>{renderAt(`/workflows/${WORKFLOW_ID}`);expect((await screen.findAllByText('Monitoring')).length).toBeGreaterThan(0);expect(screen.getAllByText('Decision').length).toBeGreaterThan(0);expect(screen.getAllByText('WAITING FOR HUMAN APPROVAL').length).toBeGreaterThan(0)})
  it('rejoue visuellement les agents sans POST ni niveau M5',async()=>{renderAt(`/workflows/${WORKFLOW_ID}/interaction`);expect(await screen.findByRole('heading',{name:'Agent Interaction'})).toBeInTheDocument();expect(await screen.findAllByText('M4 · simulation')).toHaveLength(5);const names=['Monitoring','Log Analysis','Correlation','RCA','Decision'];const nodes=names.map(name=>screen.getAllByText(name)[0]);for(let i=0;i<nodes.length-1;i++)expect(nodes[i].compareDocumentPosition(nodes[i+1])&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.queryByText(/^M5/)).not.toBeInTheDocument();expect(screen.getByText('103 ms')).toBeInTheDocument();expect(screen.getByText('67 ms')).toBeInTheDocument();expect(screen.getByText('126 ms')).toBeInTheDocument();expect(screen.getByText('53 ms')).toBeInTheDocument();expect(screen.getByText('34 ms')).toBeInTheDocument();expect(document.body).toHaveTextContent(SCORE.toFixed(6));primaryEvidence.forEach(id=>expect(screen.getByText(id)).toBeInTheDocument());fireEvent.click(screen.getByRole('button',{name:'Replay'}));fireEvent.click(screen.getByRole('button',{name:'Pause'}));for(let i=0;i<6;i++)fireEvent.click(screen.getByRole('button',{name:'Étape suivante'}));expect(screen.getAllByText('WAITING FOR HUMAN APPROVAL').length).toBeGreaterThan(0);expect(screen.getAllByText('false').length).toBeGreaterThan(0);expect(calls.every(call=>call.method==='GET')).toBe(true)},15000)
  it('expose le téléchargement du rapport version 2',async()=>{renderAt('/reports');const link=await screen.findByRole('link',{name:/Télécharger le PDF/i});expect(link).toHaveAttribute('href',`/_backend/reports/${REPORT_ID}/pdf`);expect(screen.getByText(reports[0].pdf_sha256)).toBeInTheDocument()})
  it('conserve le score déterministe exact et identifie le fallback',async()=>{renderAt('/ai-explanation');expect(await screen.findByText(SCORE.toFixed(6))).toBeInTheDocument();expect(screen.getByText('Résumé local de secours — PAS une réponse produite par le LLM.')).toBeInTheDocument();expect(screen.getAllByText('DETERMINISTIC_FALLBACK').length).toBeGreaterThan(0)})
  it('bloque l’envoi Approve et Reject en mode démonstration',async()=>{renderAt('/approval');await screen.findByRole('heading',{name:'Demande en attente'});fireEvent.change(screen.getByLabelText(/Identité/),{target:{value:'reviewer'}});fireEvent.change(screen.getByLabelText(/Commentaire/),{target:{value:'Analyse humaine documentée'}});fireEvent.click(screen.getByRole('button',{name:'Approve'}));const dialog=await screen.findByRole('dialog');expect(within(dialog).getByRole('button',{name:/Confirmer et envoyer/})).toBeDisabled();expect(calls.every(c=>c.method==='GET')).toBe(true)},15000)
  it('ne rend aucune clé ni en-tête secret dans les vues',async()=>{renderAt('/ai-explanation');await screen.findByText(/Résumé local de secours/);expect(document.body.textContent).not.toMatch(/API[_ -]?KEY|Authorization|Bearer\s/i)})
  it('affiche un état explicite lorsque l’API est indisponible',async()=>{mockApi(true);renderAt('/');expect(await screen.findByText(/API indisponible/)).toBeInTheDocument();expect(screen.getByText(/Service indisponible/)).toBeInTheDocument()})
  it('ne modifie ni workflow ni campagne pendant les tests',async()=>{renderAt('/recommendations');expect(await screen.findAllByText('executed=false')).toHaveLength(4);await waitFor(()=>expect(calls.length).toBeGreaterThan(0));expect(calls.every(c=>c.method==='GET')).toBe(true);expect(calls.some(c=>/approve|reject|advance|explanations$/.test(c.url))).toBe(false)})
})
