import { useMemo, useRef, useState } from 'react'
import { Link as RouterLink } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import {
  Alert, Button, Checkbox, Chip, Divider, FormControl, FormControlLabel, Grid,
  InputLabel, MenuItem, Paper, Select, Stack, Step, StepLabel, Stepper, Switch,
  TextField, Typography,
} from '@mui/material'
import AccountTreeRounded from '@mui/icons-material/AccountTreeRounded'
import PlayArrowRounded from '@mui/icons-material/PlayArrowRounded'
import ScienceRounded from '@mui/icons-material/ScienceRounded'
import { apiGet, apiPost, endpoints } from './api'
import { PageHeader, QueryState, SectionCard, StatusChip, pct, shortId, utc } from './components'
import { useOperationalSession } from './SessionContext'
import type { Capabilities, LiveEvent, LiveSession, LLMStatus } from './types'

type Scenario='nominal'|'battery_insufficient'|'network_unstable'|'storage_insufficient'|'package_corrupted'|'hardware_software_incompatible'|'ecu_unresponsive'|'failure_with_rollback'
type Injection={scenario:Scenario;affected_count:number|null;affected_percentage:number|null;target_hardware_revision:'ANY'|'HW_REV_A'|'HW_REV_B';error_code:string;installation_step:string;failure_probability:number}
type Draft={created_by:string;seed:number;simulation_only_confirmed:boolean;campaign:{name:string;component:string;current_version:string;target_version:string;package_type:string;package_size_mb:number;canary_strategy:string;failure_threshold:number};fleet:{vehicle_count:number;model:string;region:string;hw_rev_a:number;hw_rev_b:number;average_battery:number;average_network_quality:number;available_storage_mb:number;temperature_c:number};injections:Injection[]}
type DraftResponse={draft:Omit<Draft,'simulation_only_confirmed'>;metadata:{provider:string;model:string;writes_performed:0;actions_executed:0}}

const scenarios:Array<{key:Scenario;label:string;error:string;step:string}>=[
  {key:'nominal',label:'Scénario nominal',error:'',step:'SUCCESS'},
  {key:'battery_insufficient',label:'Batterie insuffisante',error:'BATTERY_INSUFFICIENT',step:'ELIGIBILITY_CHECK'},
  {key:'network_unstable',label:'Réseau instable',error:'NETWORK_UNSTABLE',step:'DOWNLOADING'},
  {key:'storage_insufficient',label:'Stockage insuffisant',error:'STORAGE_INSUFFICIENT',step:'ELIGIBILITY_CHECK'},
  {key:'package_corrupted',label:'Package corrompu',error:'PACKAGE_CORRUPTED',step:'VERIFYING_PACKAGE'},
  {key:'hardware_software_incompatible',label:'Incompatibilité hardware/software',error:'MEMORY_LAYOUT_MISMATCH',step:'MEMORY_VALIDATION'},
  {key:'ecu_unresponsive',label:'ECU non responsive',error:'ECU_NOT_RESPONDING',step:'REBOOTING'},
  {key:'failure_with_rollback',label:'Échec avec rollback',error:'INSTALLATION_FAILED',step:'INSTALLING'},
]
const blankDraft=():Draft=>({created_by:'ota-operator',seed:20260923,simulation_only_confirmed:false,campaign:{name:'Nouvelle simulation AIGATOS',component:'BatteryManager',current_version:'2.3.0',target_version:'2.4.0',package_type:'DELTA',package_size_mb:128,canary_strategy:'CONTROLLED',failure_threshold:.2},fleet:{vehicle_count:30,model:'AIGATOS EV',region:'EU-LAB',hw_rev_a:27,hw_rev_b:3,average_battery:82,average_network_quality:88,available_storage_mb:4096,temperature_c:24},injections:[]})
const referenceDraft=():Draft=>({...blankDraft(),campaign:{...blankDraft().campaign,name:'BatteryManager Controlled Run'},injections:[
  {scenario:'hardware_software_incompatible',affected_count:3,affected_percentage:null,target_hardware_revision:'HW_REV_B',error_code:'MEMORY_LAYOUT_MISMATCH',installation_step:'MEMORY_VALIDATION',failure_probability:1},
  {scenario:'battery_insufficient',affected_count:1,affected_percentage:null,target_hardware_revision:'ANY',error_code:'BATTERY_INSUFFICIENT',installation_step:'ELIGIBILITY_CHECK',failure_probability:1},
  {scenario:'network_unstable',affected_count:1,affected_percentage:null,target_hardware_revision:'ANY',error_code:'NETWORK_UNSTABLE',installation_step:'DOWNLOADING',failure_probability:1},
]})
const idempotencyKey=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`
const requested=(rule:Injection,total:number)=>rule.affected_count??Math.ceil(total*(rule.affected_percentage??0))

function validate(draft:Draft){
  const fields:Record<string,string>={};const blocking:string[]=[]
  if(draft.fleet.hw_rev_a+draft.fleet.hw_rev_b!==draft.fleet.vehicle_count)fields.hardware='HW_REV_A + HW_REV_B doit être égal à vehicle_count.'
  let targeted=0;const byHardware={HW_REV_A:0,HW_REV_B:0}
  for(const rule of draft.injections){const count=requested(rule,draft.fleet.vehicle_count);targeted+=count;if(count>draft.fleet.vehicle_count)fields[`${rule.scenario}.affected`]='Le nombre affecté dépasse la flotte.';if(rule.failure_probability<0||rule.failure_probability>1)fields[`${rule.scenario}.probability`]='La probabilité doit rester entre 0 et 100 %.';if(rule.scenario==='nominal'&&rule.failure_probability!==0)fields[`${rule.scenario}.probability`]='Le scénario nominal impose 0 %.';if(rule.target_hardware_revision!=='ANY')byHardware[rule.target_hardware_revision]+=count}
  if(targeted>draft.fleet.vehicle_count)blocking.push('Le total ciblé dépasse la flotte.')
  if(byHardware.HW_REV_A>draft.fleet.hw_rev_a)blocking.push('Les règles HW_REV_A dépassent la population disponible.')
  if(byHardware.HW_REV_B>draft.fleet.hw_rev_b)blocking.push('Les règles HW_REV_B dépassent la population disponible.')
  blocking.push(...Object.values(fields).filter(message=>!blocking.includes(message)))
  return {fields,blocking,targeted,nominal:Math.max(0,draft.fleet.vehicle_count-targeted)}
}

function Field({label,value,onChange,type='text',error,disabled=false}:{label:string;value:string|number;onChange:(value:string)=>void;type?:string;error?:string;disabled?:boolean}){return <TextField fullWidth label={label} value={value} type={type} disabled={disabled} error={Boolean(error)} helperText={error} onChange={event=>onChange(event.target.value)} inputProps={type==='number'?{step:'any'}:undefined}/>}

function llmUnavailableReason(status?:LLMStatus){
  if(!status?.configured)return"Assistant IA indisponible : aucun fournisseur n’est configuré. La configuration manuelle reste utilisable."
  const labels:Record<string,string>={LLM_AUTHENTICATION_FAILED:'accès refusé',LLM_PERMISSION_DENIED:'accès refusé',LLM_MODEL_NOT_FOUND:'modèle indisponible',LLM_RATE_LIMITED:'limite atteinte',LLM_CONNECT_TIMEOUT:'connexion impossible',LLM_CONNECTION_FAILED:'connexion impossible',LLM_PROXY_ERROR:'connexion impossible',LLM_INVALID_RESPONSE:'réponse invalide',LLM_VALIDATION_FAILED:'réponse invalide'}
  return `Assistant IA indisponible : ${labels[status.error_code??'']??'le fournisseur n’a pas confirmé une réponse conforme'}. La configuration manuelle reste utilisable.`
}

export function LiveSimulationPage(){
  const queryClient=useQueryClient();const {resolveAndSelect}=useOperationalSession()
  const capabilities=useQuery({queryKey:['capabilities'],queryFn:()=>apiGet<Capabilities>(endpoints.capabilities)})
  const llmStatus=useQuery({queryKey:['llm-status'],queryFn:async()=>{const configured=await apiGet<LLMStatus>(endpoints.llmStatus);if(!configured.configured)return configured;return apiPost<LLMStatus>('/api/v1/llm/test',{},idempotencyKey())},staleTime:300_000,retry:false})
  const [draft,setDraft]=useState(blankDraft);const [step,setStep]=useState(0);const [session,setSession]=useState<LiveSession|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const [prompt,setPrompt]=useState('');const [suggestion,setSuggestion]=useState<DraftResponse|null>(null)
  const keys=useRef({create:idempotencyKey(),start:idempotencyKey(),investigate:idempotencyKey()});const validation=useMemo(()=>validate(draft),[draft])
  const events=useQuery({queryKey:['live-events',session?.id],queryFn:()=>apiGet<LiveEvent[]>(endpoints.liveEvents(session!.id)),enabled:Boolean(session&&session.status!=='PREPARING'),refetchInterval:q=>session&&!['COMPLETED','FAILED','WAITING_FOR_HUMAN_APPROVAL'].includes(session.status)?3_000:false})
  const updateCampaign=(field:keyof Draft['campaign'],value:string|number)=>setDraft(current=>({...current,campaign:{...current.campaign,[field]:value}}));const updateFleet=(field:keyof Draft['fleet'],value:string|number)=>setDraft(current=>({...current,fleet:{...current.fleet,[field]:value}}))
  const updateRule=(scenario:Scenario,field:keyof Injection,value:string|number|null)=>setDraft(current=>({...current,injections:current.injections.map(rule=>rule.scenario===scenario?{...rule,[field]:value}:rule)}))
  const toggleRule=(definition:typeof scenarios[number],enabled:boolean)=>setDraft(current=>({...current,injections:enabled?[...current.injections,{scenario:definition.key,affected_count:1,affected_percentage:null,target_hardware_revision:'ANY',error_code:definition.error,installation_step:definition.step,failure_probability:definition.key==='nominal'?0:1}]:current.injections.filter(rule=>rule.scenario!==definition.key)}))
  const synchronize=async(result:LiveSession)=>{setSession(result);await resolveAndSelect(result.simulation_id);await Promise.all([['contexts'],['dashboard'],['incident'],['workflow'],['reports']].map(queryKey=>queryClient.invalidateQueries({queryKey})))}
  const mutate=async(action:()=>Promise<LiveSession>)=>{setBusy(true);setError('');try{await synchronize(await action())}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
  const generate=async()=>{setBusy(true);setError('');try{setSuggestion(await apiPost<DraftResponse>(endpoints.configurationDraft,{prompt},idempotencyKey()))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}}
  const llmAvailable=Boolean(llmStatus.data?.reachable&&llmStatus.data.authorized&&llmStatus.data.structured_output_supported&&!llmStatus.data.error_code)
  if(session)return <SessionView session={session} events={events.data??[]} busy={busy} error={error} capabilities={capabilities.data} onStart={()=>mutate(()=>apiPost(endpoints.liveStart(session.id),{},keys.current.start))} onInvestigate={()=>mutate(()=>apiPost(endpoints.liveInvestigation(session.id),{},keys.current.investigate))}/>
  return <><PageHeader eyebrow="Simulation contrôlée" title="Nouvelle simulation OTA" description="Configurez une flotte virtuelle. Chaque lancement reste une action séparée et explicite." action={<Button variant="outlined" startIcon={<ScienceRounded/>} onClick={()=>setDraft(referenceDraft())}>Charger une configuration de référence</Button>}/><QueryState loading={capabilities.isLoading} error={capabilities.error} empty={!capabilities.data}><>
    {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    {llmStatus.isLoading?<Alert severity="info" role="status">Vérification du fournisseur IA en cours. Le formulaire manuel reste disponible.</Alert>:llmStatus.isError||!llmAvailable?<Alert severity="info" role="status">{llmUnavailableReason(llmStatus.data)}</Alert>:<SectionCard title="Assistant de configuration" subtitle="Fournisseur confirmé par un appel minimal conforme. Le brouillon reste soumis à validation manuelle."><Stack direction={{xs:'column',sm:'row'}} gap={1} alignItems={{sm:'center'}} mb={2}><Chip color="success" variant="outlined" label={`Assistant disponible · ${llmStatus.data?.provider}`}/><Typography variant="caption" color="text.secondary">{llmStatus.data?.model}</Typography></Stack><TextField fullWidth multiline minRows={3} label="Description en langage naturel" value={prompt} onChange={event=>setPrompt(event.target.value)}/><Stack direction={{xs:'column',sm:'row'}} gap={1.5} mt={2}><Button variant="outlined" disabled={busy||prompt.trim().length<10} onClick={generate}>Générer le brouillon</Button>{suggestion&&<Button variant="contained" onClick={()=>{setDraft({...suggestion.draft,simulation_only_confirmed:false});setSuggestion(null)}}>Appliquer au formulaire</Button>}</Stack>{suggestion&&<Paper variant="outlined" sx={{p:2,mt:2}}><Typography fontWeight={800}>Aperçu : {suggestion.draft.campaign.name}</Typography><Typography>{suggestion.draft.fleet.vehicle_count} véhicules · {suggestion.draft.injections.length} règle(s)</Typography><Typography variant="caption">{suggestion.metadata.provider}/{suggestion.metadata.model} · écritures 0 · actions 0</Typography></Paper>}</SectionCard>}
    <Paper variant="outlined" sx={{p:3,mb:3}}><Stepper activeStep={step} alternativeLabel>{['Campagne','Flotte virtuelle','Injection contrôlée','Confirmation'].map(label=><Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper></Paper>
    {step===0&&<SectionCard title="A · Campagne virtuelle" subtitle="Package et stratégie Canary simulés"><Grid container spacing={2}><Grid size={{xs:12,md:6}}><Field label="Nom de campagne" value={draft.campaign.name} onChange={v=>updateCampaign('name',v)}/></Grid><Grid size={{xs:12,md:6}}><Field label="Composant logiciel" value={draft.campaign.component} onChange={v=>updateCampaign('component',v)}/></Grid><Grid size={{xs:6,md:3}}><Field label="Version actuelle" value={draft.campaign.current_version} onChange={v=>updateCampaign('current_version',v)}/></Grid><Grid size={{xs:6,md:3}}><Field label="Version cible" value={draft.campaign.target_version} onChange={v=>updateCampaign('target_version',v)}/></Grid><Grid size={{xs:6,md:3}}><FormControl fullWidth><InputLabel>Type de package</InputLabel><Select label="Type de package" value={draft.campaign.package_type} onChange={e=>updateCampaign('package_type',e.target.value)}><MenuItem value="DELTA">DELTA</MenuItem><MenuItem value="FULL">FULL</MenuItem></Select></FormControl></Grid><Grid size={{xs:6,md:3}}><Field type="number" label="Taille (MB)" value={draft.campaign.package_size_mb} onChange={v=>updateCampaign('package_size_mb',Number(v))}/></Grid></Grid></SectionCard>}
    {step===1&&<SectionCard title="B · Flotte virtuelle" subtitle="La répartition hardware doit couvrir exactement la flotte"><Grid container spacing={2}><Grid size={{xs:6,md:3}}><Field type="number" label="Nombre de véhicules" value={draft.fleet.vehicle_count} onChange={v=>updateFleet('vehicle_count',Number(v))}/></Grid><Grid size={{xs:6,md:3}}><Field label="Modèle" value={draft.fleet.model} onChange={v=>updateFleet('model',v)}/></Grid><Grid size={{xs:6,md:3}}><Field label="Région" value={draft.fleet.region} onChange={v=>updateFleet('region',v)}/></Grid><Grid size={{xs:6,md:3}}><Field type="number" label="Seed déterministe" value={draft.seed} onChange={v=>setDraft(c=>({...c,seed:Number(v)}))}/></Grid><Grid size={{xs:6,md:3}}><Field type="number" label="HW_REV_A" value={draft.fleet.hw_rev_a} error={validation.fields.hardware} onChange={v=>updateFleet('hw_rev_a',Number(v))}/></Grid><Grid size={{xs:6,md:3}}><Field type="number" label="HW_REV_B" value={draft.fleet.hw_rev_b} error={validation.fields.hardware} onChange={v=>updateFleet('hw_rev_b',Number(v))}/></Grid></Grid></SectionCard>}
    {step===2&&<SectionCard title="C · Injection contrôlée" subtitle={`Maximum compatible : ${draft.fleet.vehicle_count} véhicules`}><Stack spacing={2}>{scenarios.map(definition=>{const rule=draft.injections.find(item=>item.scenario===definition.key);return <Paper variant="outlined" sx={{p:2}} key={definition.key}><FormControlLabel control={<Switch checked={Boolean(rule)} onChange={(_,checked)=>toggleRule(definition,checked)}/>} label={<Typography fontWeight={800}>{definition.label}</Typography>}/>{rule&&<><Grid container spacing={1.5} mt={1}><Grid size={{xs:6,md:2}}><FormControl fullWidth><InputLabel>Impact</InputLabel><Select label="Impact" value={rule.affected_count===null?'percentage':'count'} onChange={e=>updateRule(rule.scenario,e.target.value==='count'?'affected_count':'affected_percentage',e.target.value==='count'?1:.1)}><MenuItem value="count">Nombre</MenuItem><MenuItem value="percentage">Pourcentage</MenuItem></Select></FormControl></Grid><Grid size={{xs:6,md:2}}><Field type="number" label={rule.affected_count===null?'Véhicules (%)':'Véhicules'} value={rule.affected_count??(rule.affected_percentage??0)*100} error={validation.fields[`${rule.scenario}.affected`]} onChange={v=>{const value=Number(v);updateRule(rule.scenario,rule.affected_count===null?'affected_percentage':'affected_count',rule.affected_count===null?value/100:value)}}/></Grid><Grid size={{xs:6,md:2}}><Field type="number" label="Probabilité (%)" value={rule.failure_probability*100} error={validation.fields[`${rule.scenario}.probability`]} onChange={v=>updateRule(rule.scenario,'failure_probability',Number(v)/100)}/></Grid><Grid size={{xs:6,md:2}}><FormControl fullWidth><InputLabel>Hardware</InputLabel><Select label="Hardware" value={rule.target_hardware_revision} onChange={e=>updateRule(rule.scenario,'target_hardware_revision',e.target.value)}><MenuItem value="ANY">Tous</MenuItem><MenuItem value="HW_REV_A">HW_REV_A</MenuItem><MenuItem value="HW_REV_B">HW_REV_B</MenuItem></Select></FormControl></Grid><Grid size={{xs:12,md:2}}><Field disabled label="error_code" value={rule.error_code||'—'} onChange={()=>{}}/></Grid><Grid size={{xs:12,md:2}}><Field disabled label="installation_step" value={rule.installation_step} onChange={()=>{}}/></Grid></Grid><Typography variant="body2" color="text.secondary" mt={1}>Cible {requested(rule,draft.fleet.vehicle_count)} véhicule(s), {rule.target_hardware_revision}, probabilité {pct(rule.failure_probability)} · maximum flotte {draft.fleet.vehicle_count}.</Typography></>}</Paper>})}</Stack></SectionCard>}
    {step===3&&<SectionCard title="D · Confirmation" subtitle="Synthèse calculée avant toute création"><Grid container spacing={2}><Grid size={{xs:12,md:7}}><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={850}>{draft.campaign.name}</Typography><Typography>{draft.campaign.component} {draft.campaign.current_version} → {draft.campaign.target_version}</Typography><Divider sx={{my:2}}/><Typography>Population totale : {draft.fleet.vehicle_count}</Typography><Typography>Population nominale estimée : {validation.nominal}</Typography><Typography>Véhicules ciblés : {validation.targeted}</Typography><Typography>Total restant disponible : {Math.max(0,draft.fleet.vehicle_count-validation.targeted)}</Typography><Stack direction="row" gap={1} mt={1} flexWrap="wrap">{draft.injections.map(rule=><Chip key={rule.scenario} label={`${rule.scenario}: ${requested(rule,draft.fleet.vehicle_count)}`}/>)}</Stack>{validation.blocking.length>0&&<Alert severity="error" sx={{mt:2}}>{validation.blocking.join(' · ')}</Alert>}</Paper></Grid><Grid size={{xs:12,md:5}}><Alert severity="warning" sx={{mb:2}}><strong>PÉRIMÈTRE CONTRÔLÉ</strong><br/>Aucune action OTA réelle et aucun passage automatique à Canary 3.</Alert><Field label="Créé par" value={draft.created_by} onChange={v=>setDraft(c=>({...c,created_by:v}))}/><FormControlLabel control={<Checkbox checked={draft.simulation_only_confirmed} onChange={(_,checked)=>setDraft(c=>({...c,simulation_only_confirmed:checked}))}/>} label="Je confirme une simulation sur véhicules virtuels uniquement"/></Grid></Grid></SectionCard>}
    <Stack direction="row" justifyContent="space-between" mt={3}><Button disabled={step===0} onClick={()=>setStep(value=>value-1)}>Précédent</Button>{step<3?<Button variant="contained" disabled={validation.blocking.length>0} onClick={()=>setStep(value=>value+1)}>Continuer</Button>:<Button variant="contained" disabled={busy||validation.blocking.length>0||!draft.simulation_only_confirmed||!capabilities.data?.can_create_simulation} onClick={()=>mutate(()=>apiPost(endpoints.liveSimulation(),draft,keys.current.create))}>Créer la simulation</Button>}</Stack>
  </></QueryState></>
}

function SessionView({session,events,busy,error,capabilities,onStart,onInvestigate}:{session:LiveSession;events:LiveEvent[];busy:boolean;error:string;capabilities?:Capabilities;onStart:()=>void;onInvestigate:()=>void}){
  const canStart=session.status==='PREPARING'&&capabilities?.can_launch_simulation;const canInvestigate=session.status==='INCIDENT_DETECTED'&&capabilities?.can_start_investigation
  return <><PageHeader eyebrow="Simulation contrôlée" title={String(session.configuration.campaign&&session.configuration.campaign.name)} description={`Session ${shortId(session.id)} · ${utc(session.updated_at)}`}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Alert severity="info" sx={{mb:2}}>Contexte isolé : campagne {shortId(session.campaign_id)}, simulation {shortId(session.simulation_id)}. Aucune action OTA réelle.</Alert><Stack direction={{xs:'column',md:'row'}} gap={2} mb={3}><StatusChip value={session.status}/>{canStart&&<Button variant="contained" disabled={busy} startIcon={<PlayArrowRounded/>} onClick={onStart}>Lancer la simulation</Button>}{canInvestigate&&<Button variant="contained" disabled={busy} startIcon={<AccountTreeRounded/>} onClick={onInvestigate}>Lancer l’investigation</Button>}{session.workflow_id&&<Button component={RouterLink} to="/analysis" variant="outlined">Ouvrir l’analyse agentique</Button>}</Stack><SectionCard title="Résultats persistés" subtitle={`${events.length} événements PostgreSQL`}><Grid container spacing={2}>{[['Véhicules',session.stage.vehicle_count],['Progression',`${session.stage.progress_count}/${session.stage.vehicle_count}`],['Succès',session.stage.success_count],['Échecs',session.stage.failure_count],['Rollbacks',session.stage.rollback_count]].map(([label,value])=><Grid size={{xs:6,md:2.4}} key={String(label)}><Paper variant="outlined" sx={{p:2}}><Typography variant="caption">{label}</Typography><Typography variant="h5">{value}</Typography></Paper></Grid>)}</Grid>{session.incident_id&&!session.workflow_id&&<Alert severity="warning" sx={{mt:2}}>Un incident existe. L’investigation ne démarrera qu’après action explicite.</Alert>}{!session.incident_id&&session.status==='COMPLETED'&&<Alert severity="success" sx={{mt:2}}>Aucun incident : aucune investigation n’est nécessaire.</Alert>}</SectionCard></>
}
