import { useState } from 'react'
import { Link as RouterLink, useParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import {
  Alert, Box, Button, Card, CardActionArea, CardContent, Chip, Divider, FormControl,
  Grid, InputLabel, Link, MenuItem, Paper, Select, Stack, Step, StepLabel, Stepper,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField,
  ToggleButton, ToggleButtonGroup, Typography,
} from '@mui/material'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import DownloadRounded from '@mui/icons-material/DownloadRounded'
import ArrowForwardRounded from '@mui/icons-material/ArrowForwardRounded'
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from 'recharts'
import { apiGet, apiPost, backendUrl, endpoints } from './api'
import { MetricCard, PageHeader, pct, QueryState, SectionCard, shortId, StatusChip, utc } from './components'
import { useOperationalSession } from './SessionContext'
import type { Campaign, DashboardData, Evidence, Explanation, Incident, Report, Vehicle, VehicleList } from './types'

function LabelValue({label,value}:{label:string;value:string|number}){return <Stack direction="row" justifyContent="space-between" gap={2}><Typography color="text.secondary">{label}</Typography><Typography fontWeight={700} textAlign="right">{value}</Typography></Stack>}

export function DashboardPage(){
  const {active,activeSimulationId}=useOperationalSession();const [scope,setScope]=useState<'active'|'historical'|'all'>('active')
  const query=scope==='active'&&activeSimulationId?`?simulation_id=${encodeURIComponent(activeSimulationId)}&scope=all`:`?scope=${scope}`
  const q=useQuery({queryKey:['dashboard',scope,activeSimulationId],queryFn:()=>apiGet<DashboardData>(endpoints.dashboard(query)),enabled:scope!=='active'||Boolean(activeSimulationId),refetchInterval:queryState=>queryState.state.data?.active_context&&!['COMPLETED','FAILED'].includes(queryState.state.data.active_context.simulation_status)?15_000:false})
  return <><PageHeader eyebrow="Supervision des campagnes" title="Tableau de bord" description="Vue opérationnelle du contexte PostgreSQL sélectionné." action={<Button startIcon={<RefreshRounded/>} variant="outlined" onClick={()=>q.refetch()}>Actualiser</Button>}/><ToggleButtonGroup exclusive value={scope} onChange={(_,value)=>value&&setScope(value)} sx={{mb:3}}><ToggleButton value="active">Session active</ToggleButton><ToggleButton value="historical">Historique</ToggleButton><ToggleButton value="all">Toutes les campagnes</ToggleButton></ToggleButtonGroup>{q.isLoading&&active&&<Grid container spacing={2}><Grid size={{xs:12,sm:6,lg:3}}><MetricCard label="Succès" value={active.success_count} helper={pct(1-active.failure_rate)} tone="success"/></Grid><Grid size={{xs:12,sm:6,lg:3}}><MetricCard label="Échecs" value={active.failure_count} helper={pct(active.failure_rate)} tone="error"/></Grid><Grid size={{xs:12,sm:6,lg:3}}><MetricCard label="Rollbacks" value={active.rollback_count} helper="état persistant" tone="warning"/></Grid></Grid>}<QueryState loading={q.isLoading} error={q.error} empty={!q.data}>{q.data&&<><Grid container spacing={2}>{[
      ['Véhicules',q.data.tracked_vehicle_count,`${q.data.progress_count} traités`,'primary'],['Progression',q.data.tracked_vehicle_count?`${q.data.progress_count}/${q.data.tracked_vehicle_count}`:'—','état persistant','primary'],['Succès',q.data.success_count,pct(q.data.success_rate),'success'],['Échecs',q.data.failure_count,pct(q.data.failure_rate),'error'],['Rollbacks',q.data.rollback_count,'restaurations enregistrées','warning'],['Incidents ouverts',q.data.open_incident_count,'analyse requise','warning'],['Workflows en attente',q.data.waiting_workflow_count,'validation humaine','warning'],
    ].map(([label,value,helper,tone])=><Grid key={label as string} size={{xs:12,sm:6,lg:3}}><MetricCard label={label as string} value={value as string|number} helper={helper as string} tone={tone as 'primary'|'success'|'error'|'warning'}/></Grid>)}</Grid>{scope==='active'&&active&&<Box mt={3}><SectionCard title="Contexte opérationnel actif" subtitle={`Dernière actualisation : ${utc(active.updated_at)}`}><Grid container spacing={2}><Grid size={{xs:12,md:4}}><LabelValue label="Campagne" value={active.campaign_name}/></Grid><Grid size={{xs:12,md:4}}><LabelValue label="Simulation" value={`${shortId(active.simulation_id)} · ${active.simulation_status}`}/></Grid><Grid size={{xs:12,md:4}}><LabelValue label="Workflow / agent" value={active.workflow_status??'Non démarré'}/></Grid><Grid size={{xs:12,md:4}}><LabelValue label="Validation humaine" value={active.approval_status??'Non requise'}/></Grid><Grid size={{xs:12,md:4}}><Button component={RouterLink} to="/analysis">Voir les véhicules affectés</Button></Grid><Grid size={{xs:12,md:4}}><Button component={RouterLink} to="/audit">Dernières activités agentiques</Button></Grid></Grid></SectionCard></Box>}</>}</QueryState></>
}

export function CampaignsPage(){
  const {selectSimulation}=useOperationalSession();const [scope,setScope]=useState('all');const q=useQuery({queryKey:['campaigns',scope],queryFn:()=>apiGet<Campaign[]>(`${endpoints.campaigns}?scope=${scope}`)})
  return <><PageHeader eyebrow="Supervision des campagnes" title="Campagnes" description="Campagnes historiques et simulations contrôlées, identifiées sans agrégation ambiguë."/><ToggleButtonGroup exclusive value={scope} onChange={(_,value)=>value&&setScope(value)} sx={{mb:3}}><ToggleButton value="historical">Historique</ToggleButton><ToggleButton value="live">Simulations</ToggleButton><ToggleButton value="all">Toutes</ToggleButton></ToggleButtonGroup><QueryState loading={q.isLoading} error={q.error} empty={q.data?.length===0}><Grid container spacing={2}>{q.data?.map(c=><Grid size={{xs:12,lg:6}} key={c.id}><Card><CardActionArea component={RouterLink} to={`/campaigns/${c.id}`} onClick={()=>c.simulation&&selectSimulation(c.simulation.id)}><CardContent><Stack direction="row" justifyContent="space-between" gap={2}><Box><Typography variant="h2">{c.name}</Typography><Typography color="text.secondary" mt={.5}>{c.software_package?.name} · {c.software_package?.version}</Typography></Box><Stack gap={1} alignItems="flex-end"><StatusChip value={c.status}/><Chip size="small" label={c.source==='LIVE_SIMULATION'?'SIMULATION':'HISTORIQUE'} color={c.source==='LIVE_SIMULATION'?'secondary':'default'} variant="outlined"/></Stack></Stack><Divider sx={{my:2}}/><Stack direction="row" gap={1} flexWrap="wrap">{c.simulation?.stages.map(s=><Chip key={s.id} label={`Étape ${s.stage_number} · ${s.status.replaceAll('_',' ')}`} color={s.stage_number===c.simulation?.current_stage?'primary':'default'} variant="outlined"/>)??<Chip label="Aucune simulation"/>}</Stack><Stack direction="row" justifyContent="space-between" mt={2}><Typography variant="caption" color="text.secondary">{shortId(c.id)}</Typography><ArrowForwardRounded color="primary"/></Stack></CardContent></CardActionArea></Card></Grid>)}</Grid></QueryState></>
}

export function CampaignDetailPage(){
  const {id=''}=useParams();const q=useQuery({queryKey:['campaign',id],queryFn:()=>apiGet<Campaign>(endpoints.campaign(id)),enabled:Boolean(id)})
  return <><PageHeader eyebrow="Campagne" title={q.data?.name??'Détail de campagne'} description="Progression et résultats persistés par étape."/><QueryState loading={q.isLoading} error={q.error} empty={!q.data}>{q.data&&<Grid container spacing={3}><Grid size={{xs:12,lg:8}}><SectionCard title="Progression de la campagne"><Stepper alternativeLabel activeStep={(q.data.simulation?.current_stage??1)-1}>{q.data.simulation?.stages.map(s=><Step key={s.id} completed={s.approved===true}><StepLabel optional={<Typography variant="caption">{s.status.replaceAll('_',' ')}</Typography>}>Étape {s.stage_number}</StepLabel></Step>)}</Stepper><Grid container spacing={2} mt={2}>{q.data.simulation?.stages.map(s=><Grid size={{xs:12,md:4}} key={s.id}><Paper variant="outlined" sx={{p:2}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>Étape {s.stage_number}</Typography><StatusChip value={s.status}/></Stack><Typography variant="h5" mt={2}>{s.vehicle_count} véhicules</Typography><Typography variant="body2" color="text.secondary" mt={1}>{s.success_count} succès · {s.failure_count} échecs · {s.rollback_count} rollbacks</Typography></Paper></Grid>)}</Grid></SectionCard></Grid><Grid size={{xs:12,lg:4}}><SectionCard title="Configuration"><Stack spacing={1.5}><LabelValue label="Statut" value={q.data.status}/><LabelValue label="Package" value={`${q.data.software_package?.name??'—'} ${q.data.software_package?.version??''}`}/><LabelValue label="Cible matérielle" value={q.data.software_package?.target_hardware??'—'}/><LabelValue label="Seuil d’échec" value={pct(q.data.simulation?.failure_threshold??0)}/><Alert severity="info">La progression Canary n’est jamais automatique.</Alert></Stack></SectionCard></Grid></Grid>}</QueryState></>
}

export function VehiclesPage(){
  const {activeSimulationId}=useOperationalSession();const [search,setSearch]=useState('');const [hardware,setHardware]=useState('');const [status,setStatus]=useState('');const [scope,setScope]=useState<'active'|'historical'|'all'>('active');const params=new URLSearchParams();if(search)params.set('q',search);if(hardware)params.set('hardware_revision',hardware);if(status)params.set('ota_status',status);if(scope==='active'&&activeSimulationId)params.set('simulation_id',activeSimulationId);else params.set('scope',scope);params.set('limit','250');const q=useQuery({queryKey:['vehicles',scope,activeSimulationId,search,hardware,status],queryFn:()=>apiGet<VehicleList>(endpoints.vehicles(`?${params}`)),enabled:scope!=='active'||Boolean(activeSimulationId)})
  return <><PageHeader eyebrow="Flotte" title="Véhicules" description="Inventaire et chronologies OTA du contexte sélectionné."/><Card sx={{mb:3}}><CardContent><Grid container spacing={2}><Grid size={{xs:12,md:4}}><TextField fullWidth label="Rechercher par VIN ou modèle" value={search} onChange={e=>setSearch(e.target.value)}/></Grid><Grid size={{xs:6,md:2}}><FormControl fullWidth><InputLabel>Hardware</InputLabel><Select label="Hardware" value={hardware} onChange={e=>setHardware(e.target.value)}><MenuItem value="">Tous</MenuItem><MenuItem value="HW_REV_A">HW_REV_A</MenuItem><MenuItem value="HW_REV_B">HW_REV_B</MenuItem></Select></FormControl></Grid><Grid size={{xs:6,md:2}}><FormControl fullWidth><InputLabel>État OTA</InputLabel><Select label="État OTA" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="">Tous</MenuItem><MenuItem value="SUCCESS">Succès</MenuItem><MenuItem value="FAILURE">Échec</MenuItem><MenuItem value="NOT_STARTED">Non démarré</MenuItem></Select></FormControl></Grid><Grid size={{xs:12,md:4}}><ToggleButtonGroup fullWidth exclusive value={scope} onChange={(_,value)=>value&&setScope(value)}><ToggleButton value="active">Session active</ToggleButton><ToggleButton value="historical">Historique</ToggleButton><ToggleButton value="all">Toutes</ToggleButton></ToggleButtonGroup></Grid></Grid></CardContent></Card><QueryState loading={q.isLoading} error={q.error} empty={q.data?.items.length===0}><TableContainer component={Paper}><Table aria-label="Liste des véhicules"><TableHead><TableRow><TableCell>Véhicule</TableCell><TableCell>Source</TableCell><TableCell>ECU</TableCell><TableCell>Hardware</TableCell><TableCell>Version</TableCell><TableCell>État OTA</TableCell></TableRow></TableHead><TableBody>{q.data?.items.map(v=><TableRow key={v.id} hover><TableCell><Link component={RouterLink} to={`/vehicles/${v.id}`} fontWeight={750}>{v.model}</Link><Typography variant="caption" display="block" color="text.secondary">{v.vin}</Typography></TableCell><TableCell>{v.source==='LIVE_SIMULATION'?'Simulation':'Historique'}</TableCell><TableCell>{v.ecu?.name??'—'}</TableCell><TableCell>{v.hardware_revision}</TableCell><TableCell>{v.current_version??'—'} → {v.target_version??'—'}</TableCell><TableCell><StatusChip value={v.ota_status}/></TableCell></TableRow>)}</TableBody></Table></TableContainer></QueryState></>
}

export function VehicleDetailPage(){const {id=''}=useParams();const q=useQuery({queryKey:['vehicle',id],queryFn:()=>apiGet<Vehicle>(endpoints.vehicle(id)),enabled:Boolean(id)});return <><PageHeader eyebrow="Véhicule" title={q.data?.model??'Détail du véhicule'} description={q.data?.vin??'Chronologie OTA enregistrée'}/><QueryState loading={q.isLoading} error={q.error} empty={!q.data}>{q.data&&<Grid container spacing={3}><Grid size={{xs:12,md:4}}><SectionCard title="Identité"><Stack spacing={1.5}><LabelValue label="Région" value={q.data.region??'Non renseignée'}/><LabelValue label="ECU" value={q.data.ecu?.name??'—'}/><LabelValue label="Hardware" value={q.data.hardware_revision}/><LabelValue label="Version" value={`${q.data.current_version} → ${q.data.target_version}`}/><LabelValue label="Rollback" value={q.data.rolled_back?'Oui':'Non'}/><StatusChip value={q.data.ota_status}/></Stack></SectionCard></Grid><Grid size={{xs:12,md:8}}><SectionCard title="Timeline des événements"><Stack divider={<Divider flexItem/>}>{q.data.timeline?.map(e=><Stack key={e.event_id} direction="row" gap={2} py={1.3}><Typography variant="caption" color="text.secondary" minWidth={150}>{utc(e.timestamp)}</Typography><Box><Typography fontWeight={750}>{e.installation_step}</Typography><Typography variant="body2" color={e.error_code?'error':'text.secondary'}>{e.error_code??e.event_type}</Typography></Box></Stack>)}</Stack></SectionCard></Grid></Grid>}</QueryState></>}

export function IncidentPage(){
  const {active}=useOperationalSession();const id=active?.incident_id??'';const incident=useQuery({queryKey:['incident',id],queryFn:()=>apiGet<Incident>(endpoints.incident(id)),enabled:Boolean(id),refetchInterval:15_000});const evidence=useQuery({queryKey:['evidence',id],queryFn:()=>apiGet<Evidence[]>(endpoints.evidence(id)),enabled:Boolean(id),refetchInterval:15_000})
  if(!id)return <><PageHeader eyebrow="Analyse d’incident" title="Incidents" description="Aucun incident n’est associé au contexte actif."/><Alert severity="info">Sélectionnez une session contenant un incident.</Alert></>
  return <><PageHeader eyebrow="Analyse d’incident" title={incident.data?.title??'Incident'} description={`Incident ${shortId(id)}`} action={incident.data&&<StatusChip value={incident.data.status}/>}/><QueryState loading={incident.isLoading||evidence.isLoading} error={incident.error??evidence.error} empty={!incident.data}>{incident.data&&<><Grid container spacing={2}>{[
    ['Véhicules',incident.data.vehicle_count,'population analysée','primary'],['Succès',incident.data.success_count,'exécutions réussies','success'],['Échecs',incident.data.failure_count,pct(incident.data.failure_rate),'error'],['Rollbacks',incident.data.rollback_count,'restaurations','warning'],['Preuves',incident.data.linked_event_count,`${incident.data.failure_event_count} événements d’échec`,'primary'],
  ].map(([label,value,helper,tone])=><Grid size={{xs:6,md:4,lg:2.4}} key={label as string}><MetricCard label={label as string} value={value as string|number} helper={helper as string} tone={tone as 'primary'|'success'|'error'|'warning'}/></Grid>)}</Grid><Grid container spacing={3} mt={.5}><Grid size={{xs:12,lg:7}}><SectionCard title="Résultats par révision matérielle" subtitle="Effectifs calculés depuis PostgreSQL"><Box height={300}><ResponsiveContainer width="100%" height="100%"><BarChart data={incident.data.hardware_distribution}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="hardware_revision"/><YAxis allowDecimals={false}/><ChartTooltip/><Legend/><Bar dataKey="success" name="Succès" fill="#16845b"/><Bar dataKey="failure" name="Échecs" fill="#c4323f"/></BarChart></ResponsiveContainer></Box></SectionCard></Grid><Grid size={{xs:12,lg:5}}><SectionCard title="Erreurs normalisées"><Stack divider={<Divider flexItem/>}>{incident.data.normalized_errors.map(e=><Stack key={`${e.error_code}-${e.installation_step}`} py={1.1} direction="row" justifyContent="space-between" gap={2}><Box><Typography fontWeight={750}>{e.error_code}</Typography><Typography variant="caption" color="text.secondary">{e.installation_step}</Typography></Box><Chip label={e.count}/></Stack>)}</Stack></SectionCard></Grid><Grid size={12}><SectionCard title="Preuves PostgreSQL" subtitle="Identifiants techniques consultables sans modification"><TableContainer sx={{maxHeight:380}}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>Evidence ID</TableCell><TableCell>Véhicule</TableCell><TableCell>Étape</TableCell><TableCell>Erreur</TableCell><TableCell>Hardware</TableCell></TableRow></TableHead><TableBody>{evidence.data?.map(e=><TableRow id={`evidence-${e.evidence_id}`} key={e.evidence_id}><TableCell title={e.evidence_id}>{shortId(e.evidence_id)}</TableCell><TableCell>{shortId(e.vehicle_id)}</TableCell><TableCell>{e.installation_step}</TableCell><TableCell>{e.error_code??'—'}</TableCell><TableCell>{e.hardware_revision}</TableCell></TableRow>)}</TableBody></Table></TableContainer></SectionCard></Grid></Grid></>}</QueryState></>
}

export function ReportsPage(){
  const queryClient=useQueryClient();const {active,resolveAndSelect}=useOperationalSession();const id=active?.incident_id??'';const [generationError,setGenerationError]=useState('');const [generating,setGenerating]=useState(false)
  const reports=useQuery({queryKey:['reports',id],queryFn:()=>apiGet<Report[]>(endpoints.reports(id)),enabled:Boolean(id)});const terminal=Boolean(active?.workflow_status&&['WAITING_FOR_HUMAN_APPROVAL','COMPLETED','APPROVED','REJECTED'].includes(active.workflow_status));const explanation=useQuery({queryKey:['explanation',id],queryFn:()=>apiGet<Explanation>(endpoints.explanation(id)),enabled:Boolean(id&&active?.workflow_id&&terminal),retry:false});const latest=reports.data?.[0]
  const generate=async()=>{if(!id||!active?.workflow_id||!explanation.data)return;setGenerating(true);setGenerationError('');try{await apiPost<Report>(endpoints.createReport(id),{workflow_id:active.workflow_id,explanation_id:explanation.data.id},globalThis.crypto?.randomUUID?.()??String(Date.now()));await queryClient.invalidateQueries({queryKey:['reports',id]});await resolveAndSelect(active.simulation_id)}catch(reason){setGenerationError(reason instanceof Error?reason.message:String(reason))}finally{setGenerating(false)}}
  if(!id)return <><PageHeader eyebrow="Historique documentaire" title="Rapports" description="Aucun incident sélectionné."/><Alert severity="info">Sélectionnez une session contenant un incident.</Alert></>
  if(!active?.workflow_id)return <><PageHeader eyebrow="Historique documentaire" title="Rapports" description="Incident sans workflow."/><Alert severity="info">Lancez d’abord explicitement l’investigation depuis la page Analyse agentique.</Alert></>
  if(!terminal)return <><PageHeader eyebrow="Historique documentaire" title="Rapports" description="Investigation en cours."/><Alert severity="info">Le rapport sera disponible quand le workflow aura atteint un état terminal. L’analyse n’est pas relancée ici.</Alert></>
  return <><PageHeader eyebrow="Historique documentaire" title="Rapports" description="Versions archivées de l’incident actif."/>{generationError&&<Alert severity="error" sx={{mb:2}}>{generationError}</Alert>}{reports.isLoading?<Alert severity="info">Chargement des rapports…</Alert>:reports.error?<Alert severity="error" action={<Button onClick={()=>reports.refetch()}>Réessayer</Button>}>Impossible de charger les rapports.</Alert>:!latest?<Alert severity="info" action={explanation.data?<Button disabled={generating} onClick={generate}>Générer le rapport</Button>:undefined}>L’analyse est disponible, mais aucun rapport archivé n’a encore été généré.{explanation.isError&&' Aucune explication persistée compatible n’est disponible.'}</Alert>:<Grid container spacing={3}><Grid size={{xs:12,lg:7}}><SectionCard title={`Rapport version ${latest.version}`} subtitle={`Généré ${utc(latest.generated_at)}`}><Stack spacing={1.5}><LabelValue label="Incident" value={shortId(latest.incident_id)}/><LabelValue label="Workflow" value={shortId(latest.workflow_id)}/><LabelValue label="Rapport" value={shortId(latest.report_id)}/><LabelValue label="Template" value={latest.template_version}/><Divider/><Typography variant="caption" color="text.secondary">SHA-256</Typography><Typography fontFamily="monospace" sx={{wordBreak:'break-all'}}>{latest.pdf_sha256}</Typography><Button component="a" href={backendUrl(latest.download_url)} download startIcon={<DownloadRounded/>} variant="contained" sx={{alignSelf:'flex-start'}}>Télécharger le PDF</Button></Stack></SectionCard></Grid><Grid size={{xs:12,lg:5}}><SectionCard title="Versions disponibles"><Stack divider={<Divider flexItem/>}>{reports.data?.map(report=><Stack key={report.report_id} py={1.5} direction="row" justifyContent="space-between"><Typography fontWeight={800}>Version {report.version}</Typography><Button component="a" href={backendUrl(report.download_url)} aria-label={`Télécharger rapport version ${report.version}`}><DownloadRounded/></Button></Stack>)}</Stack></SectionCard></Grid></Grid>}</>
}

export function NotFoundPage(){return <><PageHeader title="Page introuvable" description="La ressource demandée n’existe pas dans l’interface AIGATOS."/><Button component={RouterLink} to="/" variant="contained">Retour au tableau de bord</Button></>}
