export type ServiceState = 'opérationnel' | 'indisponible'
export interface OperationalContext { context_id:string;source:'LIVE_SIMULATION'|'HISTORICAL_VALIDATED';environment:'SIMULATED';session_id:string|null;campaign_id:string;campaign_name:string;campaign_status:string;simulation_id:string;simulation_status:string;incident_id:string|null;workflow_id:string|null;report_id:string|null;workflow_status:string|null;approval_status:string|null;software_name:string|null;software_version:string|null;stage_number:number;vehicle_count:number;progress_count:number;success_count:number;failure_count:number;rollback_count:number;failure_rate:number;evidence_count:number;global_confidence:number|null;actions_executed:number;created_by:string;created_at:string;updated_at:string }
export interface DashboardData { scope:string;active_context:OperationalContext|null;campaign_count:number;tracked_vehicle_count:number;simulation_participant_count:number;progress_count:number;success_count:number;failure_count:number;rollback_count:number;success_rate:number;failure_rate:number;open_incident_count:number;waiting_workflow_count:number;services:Record<string,ServiceState> }
export interface Stage { id:string; stage_number:number; vehicle_count:number; status:string; success_count:number; failure_count:number; rollback_count:number; approved:boolean|null; evaluated_by:string|null; evaluated_at:string|null }
export interface Campaign { id:string; name:string; status:string; canary_percentage:number; created_at:string; source?:'LIVE_SIMULATION'|'HISTORICAL_VALIDATED';session_id?:string|null;software_package:{id:string;name:string;version:string;target_hardware:string}|null; simulation:{id:string;status:string;current_stage:number;failure_threshold:number;stages:Stage[]}|null }
export interface Vehicle { id:string; vin:string; model:string; region:string|null; hardware_revision:string; ecu:{id:string;name:string}|null; current_version:string|null; target_version:string|null; ota_status:string; rolled_back:boolean; simulation_id:string|null; campaign_id:string|null;source?:'LIVE_SIMULATION'|'HISTORICAL_VALIDATED';session_id?:string|null; timeline?:TimelineEvent[] }
export interface TimelineEvent { event_id:string; timestamp:string; event_type:string; installation_step:string; error_code:string|null; battery_level:number; network_quality:number; free_storage_mb:number }
export interface VehicleList { total:number; items:Vehicle[] }
export interface AffectedVehicle { vehicle_id:string;vin:string;hardware_revision:string|null;last_successful_step:string|null;failure_step:string|null;error_code:string|null;rolled_back:boolean;analysis_agent:string|null;evidence_ids:string[] }
export interface Incident { id:string;campaign_id:string;simulation_id:string;stage_number:number;status:string;severity:string;title:string;failure_rate:number;threshold:number;anomaly_score:number|null;created_at:string;vehicle_count:number;success_count:number;failure_count:number;rollback_count:number;linked_event_count:number;failure_event_count:number;workflow_id:string|null;workflow_status:string|null;active_agent:string|null;approval_status:string|null;affected_vehicles:AffectedVehicle[];normalized_errors:Array<{error_code:string;installation_step:string;count:number}>;hardware_distribution:Array<{hardware_revision:string;total:number;success:number;failure:number}> }
export interface Evidence { evidence_id:string;evidence_type:string;event_id:string;vehicle_id:string;sequence:number;timestamp:string;installation_step:string;error_code:string|null;hardware_revision:string;software_version:string;battery_level:number;network_quality:number;free_storage_mb:number }
export interface Workflow { workflow_id:string;incident_id:string;campaign_id:string;canary_stage_id:string;current_agent:string|null;workflow_status:string;failed_vehicle_ids:string[];successful_vehicle_ids:string[];normalized_errors:Array<Record<string,unknown>>;timeline:Array<Record<string,unknown>>;correlations:Array<Record<string,unknown>>;hypotheses:Array<{hypothesis_id:string;factor:string;level:string;statement:string;confidence:number;rank:number;evidence_ids:string[];score_components:Record<string,number>}>;evidence_ids:string[];confidence_components:Record<string,number>;global_confidence:number|null;recommended_actions:Array<{action:string;status:string;requires_human_approval:boolean;reason:string;executed:boolean;evidence_ids:string[]}>;approval_status:string;retry_count:number;last_error:string|null;created_at:string;updated_at:string }
export interface History { id:string;sequence:number;agent:string;event_type:string;input_summary:Record<string,unknown>;output_summary:Record<string,unknown>;duration_ms:number;error_type:string|null;error_message:string|null;created_at:string }
export interface AgentExecution { id:string;agent_type:string;objective:string;status:string;tools_allowed:string[];tools_used:string[];input_payload:Record<string,unknown>;output_payload:Record<string,unknown>;evidence_ids:string[];incoming_message_ids:string[];outgoing_message_ids:string[];validations:string[];attempt:number;duration_ms:number;proposed_next_state:string|null;output_source:string;error_code:string|null;created_at:string;completed_at:string|null }
export interface AgentMessage { id:string;sender_agent:string;receiver_agent:string;message_type:string;payload:Record<string,unknown>;evidence_ids:string[];correlation_id:string;sequence_number:number;validation_status:string;created_at:string;consumed_at:string|null }
export interface ToolExecution { id:string;agent_execution_id:string;agent_type:string;tool_name:string;mode:string;input_payload:Record<string,unknown>;output_payload:Record<string,unknown>;status:string;duration_ms:number;sequence_number:number;created_at:string }
export interface LLMStatus { provider:string|null;model:string|null;hostname:string;configured:boolean;reachable:boolean;authorized:boolean;latency_ms:number|null;structured_output_supported:boolean;error_code:string|null }
export interface Report { report_id:string;incident_id:string;workflow_id:string;explanation_id:string;version:number;template_version:string;pdf_sha256:string;generated_at:string;download_url:string;source:string|null }
export interface Explanation { id:string;workflow_id:string;incident_id:string;provider:string;model_name:string;prompt_version:string;source:string;status:string;duration_ms:number;created_at:string;output:{incident_summary:string;probable_root_cause:string;confidence_interpretation:string;evidence_citations:Array<{evidence_id:string;statement:string}>;alternative_hypotheses:string[];recommended_next_steps:string[];limitations:string[];generated_at:string;model_name:string;prompt_version:string} }
export interface Capabilities { operation_mode:'readonly_demo'|'live_simulation';can_create_simulation:boolean;can_launch_simulation:boolean;can_start_investigation:boolean;can_review_recommendations:boolean;can_execute_real_ota:false }
export interface LiveEvent { event_id:string;timestamp:string;vehicle_id:string;event_type:string;installation_step:string;error_code:string|null;hardware_revision:string;battery_level:number;network_quality:number;free_storage_mb:number }
export interface LiveSession { id:string;session_id:string;source:'LIVE_SIMULATION';environment:'SIMULATED';created_by:string;created_at:string;updated_at:string;status:string;campaign_id:string;simulation_id:string;incident_id:string|null;workflow_id:string|null;configuration:Record<string,any>;result:Record<string,any>;current_stage:number;stage:{stage_number:number;vehicle_count:number;status:string;success_count:number;failure_count:number;rollback_count:number;progress_count:number};event_count:number;workflow:Workflow|null;executed:false;can_execute_real_ota:false;created?:boolean;decision_recorded?:boolean;message?:string }
export interface LiveWorkflow extends Workflow { history:History[];source:string;environment:string;session_id:string }
export interface MaturityCriterion { satisfied:boolean;label:string }
export interface AgentMaturity { agent:string;name:string;role:string;current_level:string;execution_status:string;criteria:Record<string,MaturityCriterion>;technical_evidence:string[];associated_tests:string[];last_execution:string|null;duration_ms:number|null;input_summary:Record<string,unknown>;output_summary:Record<string,unknown>;recent_errors:string[];limitations:string[];next_level:string;next_level_conditions:string[] }
export interface MaturityResponse { scale:Array<{level:string;label:string}>;agents:AgentMaturity[];certification_notice:string;m5_available:false }
export interface AuditEntry { id:string;timestamp:string;category:'SIMULATION'|'AGENT';actor:string;action:string;status:string;summary:string;details:Record<string,unknown> }
export interface AuditResponse { context:OperationalContext;entries:AuditEntry[] }
